### ISSUE TITLE
Default value for code_version

### ISSUE THREAD

**Issue by PoslinskiNet** [Exelord/ember-rollbar-client#10]
It would be cool to fetch as a default value (if no provided via config) code version similar to what `ember-cli-app-version` does in Ember inspector.

I think that might be useful:
https://github.com/EmberSherpa/ember-cli-app-version/blob/master/app/helpers/app-version.js

**Comment by Exelord** [comment]
That's cool! But require also: https://github.com/EmberSherpa/ember-cli-app-version#heroku
There is some work which will introduce that in #4
