### ISSUE TITLE
Latest version 0.5.0 breaks all the things

### ISSUE THREAD

**Issue by sdhull** [Exelord/ember-rollbar-client#14]
I can't quit explain _why_ this happens but we recently upgraded to 0.5.0 and found that:
1. ember errors were not coming through to console in development (even though we have rollbar disabled for all environments except production)
2. Various things in our app were silently breaking (again, no errors)

Rolling back to 0.4.0 fixed our app. Sorry I don't have a good way to repro the issues nor time to figure out how to repro right now. I guess it's possibly a regression in some of the other dependencies that are updated as a result. I'll try to figure out how to repro the issue later, but wanted to leave this here in case anyone else has trouble with the latest version.

It would be nice if you could release a 0.4.1 version with _only_ updated rollbar.js library.

**Comment by Exelord** [comment]
Hmm, thank you very much for reporting this! I will defiantly take a look at this this weekend

**Comment by Exelord** [comment]
Fixed in v0.5.1, could you confirm?

**Comment by sdhull** [comment]
Seems to work 👍
