### ISSUE TITLE
Errors thrown using Ember.Logger.error are not reported

### ISSUE THREAD

**Issue by lucasalencar** [Exelord/ember-rollbar-client#16]
When some error is logged using `Ember.Logger.error`, they are not reported to Rollbar. Does it make sense to log them?

## Context

I have an app that was using [ember-cli-rollbar](https://github.com/davewasmer/ember-cli-rollbar) to report errors. We chose them because it was the rollbar team recommendation.

But unfortunately, the package is not updated very often. So I decided to use this package instead. (good job with the project BTW).

When I changed the package, I noticed that some errors were not being logged as the previous package.

Investigating it better I found that ember-cli-rollbar was registering all the errors logged to `Ember.Logger.error`. You can see it [here](https://github.com/davewasmer/ember-cli-rollbar/blob/master/app/initializers/rollbar.js).

I have implemented an initializer in my application to catch these errors. To avoid changing the previous behavior.

My question is, does it make sense to have this feature in this package?

**Comment by Exelord** [comment]
Hey,
Which version are you using? We had a problem with logging in 0.5.0 which is fixed now in 0.5.1.

According to `Ember.Logger.error` - we are not handling it as this is just a log, not an ember error.
We are handling all errors form `Ember.onerror` and JS itself.
In the readme, there is also an example how to handle "all" RSVP errors.

If you would like to handle logs from internal Logger method then you have to cover it by yourself :/ This is a custom behavior which does not apply to all cases.

**Comment by lucasalencar** [comment]
I am using 0.5.0 version, but the report is not the issue.

I have an example case. In my application, I have an error log being shown in production that made me identify an event leak in our code. It was listening events to an element that did not exist anymore.

So, in this case, I managed to find an error in production, because everything being logged to Ember.Logger.error was being reported.

I don't know exactly which kinds of errors go to Ember.Logger and which ones go through Ember.onerror. :\

But in this case, I preferred to make sure that even these errors being logged by Ember.Logger are reported to Rollbar.

**Comment by sdhull** [comment]
Coincidentally, 0.5.1 seemed to be OK initially but recently (was the package updated on npm?) it seems to be once again swallowing errors so nothing gets output to console in development 😞

**Comment by sdhull** [comment]
We've just downgraded back to 0.40 for now :(

**Comment by Exelord** [comment]
Ember.Logger has been deprecated. Issue is no more valid
