### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by lolmaus** [Exelord/ember-rollbar-client#22]
Error in browser console:

> Rollbar: Error: The response from the provider is missing these required response params: code

![image](https://user-images.githubusercontent.com/200884/34571041-9762cd20-f17e-11e7-9e41-01d207e7dcce.png)

Error in Rollbar dashboard:

> Error: code

![image](https://user-images.githubusercontent.com/200884/34571071-a6a64186-f17e-11e7-8d83-74695710b1ca.png)

The full error message is accessible when I expand `Telemetry` in the Rollbar dashboard. But I want it to be visible in the listing!

Here's the payload of the report: https://gist.github.com/lolmaus/da6a3d050769fc4e1bf8da07fe91d965

The problematic part seems to be `"message": "code"`.

**Comment by Exelord** [comment]
Hey, I also encountered that kind of problem. It looks like this is a Rollbar issue.
If I send to the Rollbar manually two issues:
```
        "exception": {
          "class": "Error",
          "message": "test"
        },
```

```
"exception": {
  class: "ReferenceError"
  message: "a is not defined"
}
```

The second one will be displayed correctly but the first one not :/
