### ISSUE TITLE
Errors crash server in development mode

### ISSUE THREAD

**Issue by nolman** [Exelord/ember-rollbar-client#29]
Hi Exelord, appreciate you making this addon. I am not sure if you are aware that `ember-rollbar-client` will crash an app in development that is running fastboot and reporting is disabled (we don't report errors on our dev box to rollbar).

Here is the line of code that causes the crash: https://github.com/Exelord/ember-rollbar-client/blob/master/addon/instance-initializers/rollbar.js#L16

**Comment by Exelord** [comment]
Isn't it correct behavior? The problem is not that I rethrow the error (which is by default if you comment out the `.onerror` hook) but the error itself. What is it saying?

**Comment by Exelord** [comment]
Ok, I see the problem ;) Im on it! Thanks for reporting!

**Comment by Exelord** [comment]
Wow... that's weird. It looks like we can throw anything inside of Ember.onerror in fastboot. The Q is why?

**Comment by Exelord** [comment]
Fixed :)

**Comment by nolman** [comment]
Thanks for fixing this @Exelord!
