### ISSUE TITLE
Consider removing lodash as a dependency

### ISSUE THREAD

**Issue by jonpitch** [Exelord/ember-rollbar-client#34]
The [rollbar service](https://github.com/Exelord/ember-rollbar-client/blob/master/addon/services/rollbar.js#L5) depends on `lodash`, so consuming apps get a lot of code bundled into their `vendor.js`.

## Steps to reproduce
- `npm install -g broccoli-concat-analyser`
- `ember new rollbar-demo`
- `cd rollbar-demo`
- `CONCAT_STATS=true ember s -e production`
- kill ember server once up
- `broccoli-concat-analyser ./concat-stats-for`

Result:
![ember new](https://user-images.githubusercontent.com/8667703/42060330-73c9cdaa-7af4-11e8-9d81-60a916350ab0.png)

- `ember install ember-rollbar-client`
- `CONCAT_STATS=true ember s -e production`
- kill ember server once up
- `broccoli-concat-analyser ./concat-stats-for`

Result:
![with ember-rollbar-client](https://user-images.githubusercontent.com/8667703/42060364-8c9dc782-7af4-11e8-9432-1fcfff739f50.png)

Note the extra 163k in `vendor.js`. Let me know if I can help in any way.

**Comment by Exelord** [comment]
Wow nice tool I didn't know about that, thanks! Yes we should improve it I agree!

**Comment by kimek** [comment]
It will be amazing if this will be possible. Now 1/4 of our vendor is lodash :(
