### ISSUE TITLE
Warning from ember-cli-cjs-transform when upgrading to 0.8.0

### ISSUE THREAD

**Issue by richard-viney** [Exelord/ember-rollbar-client#41]
After upgrading from 0.7.1 to 0.8.0 am seeing the following warning on build:

`WARNING: Addon "ember-cli-cjs-transform" is defining a transform name: cjs that is already being defined. Using transform from addon: "ember-cli-cjs-transform"`

I'm also using the `ember-useragent` addon that depends on `ember-cli-cjs-transform`. Do the two need to co-operate better somehow?

Thanks.

**Comment by Exelord** [comment]
this is the `ember-cli-cjs-transform` bug. Nothing to worry about. https://github.com/rwjblue/ember-cli-cjs-transform/issues/22

its just a warning until they fix it :)
