### ISSUE TITLE
update rollbar

### ISSUE THREAD

**Issue by xn** [Exelord/ember-rollbar-client#5]
can we get a version update to ~2.2.0 please?

**Comment by NullVoxPopuli** [comment]
is there anyway we can manage the rollbar dependency ourselves? just if we want to keep up with updates?

**Comment by Exelord** [comment]
Updates are coming soon :)

**Comment by NullVoxPopuli** [comment]
yay!

**Comment by Exelord** [comment]
Merged in #7 and released as v0.4.0

**Comment by NullVoxPopuli** [comment]
woo!
