### ISSUE TITLE
There's no automatic logger for RSVP errors.

### ISSUE THREAD

**Issue by viniciussbs** [Exelord/ember-rollbar-client#6]
The README says

> Automatic logger for:
> - js window errors
> - ember errors
> - rsvp errors

But [the service only registers a logger for Ember errors](https://github.com/Exelord/ember-rollbar-client/blob/master/addon/services/rollbar.js#L53-L62). Or does `Ember.onerror` catch RSVP errors? [Ember docs](https://www.emberjs.com/api/ember/2.15/namespaces/Ember/events/onerror?anchor=onerror) doesn't mention that.

**Comment by Exelord** [comment]
Yes, sorry. That feature was removed due to `TransitionAborted` errors.
I added an instruction to README in https://github.com/Exelord/ember-rollbar-client/pull/7
