### ISSUE TITLE
Filter what is reported

### ISSUE THREAD

**Issue by boyanyordanov** [Exelord/ember-rollbar-client#8]
Thanks for the addon. It does indeed work as expected. 

There's only one thing we found lacking from our implementation before that.

For some of the data we rely only on backend validation, so sometimes there are a lot of 422 responses that get sent to rollbar, but are actually expected. The same goes for 401s when a token expires and a few others.

My solution currently is to extend the exposed rollbar service and override the `registerLogger` method to invoke a method that decides whether to report the error to rollbar or not. 

It looks like this: 

```
registerLogger() {
        if (this.get('enabled')) {
            let oldOnError = Ember.onerror || function() {};

            Ember.onerror = (...args) => {
                oldOnError(...args);

                if (this.shouldReport(...args)) {
                    this.error(...args);
                }
            };
        }
    }
```

And then the `shouldReport` method inspects the error and decides whether to report it or not. 

Is this a good way to go about it? 
And would you consider adding something like this ?

If it's in the addon with a default implmentation for the `shouldReport` method that just returns `true`, then anyone can simply extend the service and override it to add their own logic.

I can do a PR if you think this is good or have any suggestions on how to handle this case better.

**Comment by Exelord** [comment]
Hi :)
What about this solution? From official Rollbar doc https://github.com/rollbar/rollbar.js#context-1
I think it will help you to filter which kind of errors you want to sent to Rollbar.

<img width="877" alt="screen shot 2017-09-17 at 18 49 18" src="https://user-images.githubusercontent.com/1469375/30522975-f0b155e6-9bd8-11e7-84b5-3d55690bd8d4.png">

**Comment by boyanyordanov** [comment]
Thank you! I din't even notice this in the docs.
 
Unfortunately Ember Cli seems to filter out functions from the config (or I am doing something wrong). 

Any suggestions where to place that without tinkering with the addon?

**Comment by boyanyordanov** [comment]
Nevermind I created a instance initializer and do a `configure` call to add the`checkIgnore` callback. Perhaps it's worth adding that to the docs?

However the `args` parameter is always `undefined`. I did a trace with the debugger and it seems to be a problem with rollbar itself. I'll try to verify that and open an issue on their repository. I think this issue can be closed now..

**Comment by Exelord** [comment]
You can configure it in the environment file. like the doc says.
https://github.com/Exelord/ember-rollbar-client#configuration
